### ISSUE TITLE
Crash on server

### ISSUE THREAD

**Issue by pupnewfster** [Lorexe/MekaTweaker#4]
Crash on server with mekatweaker version 1.1.1
Resource Loader is a client side only mod. It should not be required on servers as the servers do not need (or even have) access to textures.

```
net.minecraftforge.fml.common.MissingModsException: Mod mekatweaker (MekaTweaker) requires [resourceloader]
    at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:264)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:125)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by kobaltromero** [comment]
I'd just add resource loader and leave it alone. That's what I'd do. I'm sure Lorexe has a reason for depending it on both client and server. :P

**Comment by pupnewfster** [comment]
ResourceLoader is a client side only mod. That means it does not load on the server so cannot be found by MekaTweaker. That is the problem with how it is.

**Comment by kobaltromero** [comment]
Okay, I got you now. Sorry. Lol

**Comment by Lorexe** [comment]
Yeah I forgot it is only client side and yes it is totally useless server side...
I will change that as soon as I can (couple of days)
